### ISSUE TITLE
GPL-764 Do not update DART if the MLWH insert fails

### ISSUE THREAD

**Issue by Chris-Friend** [sanger/crawler#162]
**User story**
As developers we do not want sample data to be inserted into DART if inserts into MLWH fail. This will ensure the three databases are in as consistent a state as possible: if mongo fails insert, we don't insert into

**Who are the primary contacts for this story**
Chris F
Phil

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Don't insert into DART if insert into MLWH fails (should just be returning a bool from the MLWH insert function, and checking this before inserting into DART)
- [x] Add tests for the above

**Dependencies**
No dependencies

**Additional context**
Error type descriptions already updated on https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/i.+Low+Occupancy+Cherry+Picking

**Comment by harrietc52** [comment]
might be best to branch off GPL-733 as that contains lots of style changes.

- insert_samples_from_docs_into_mlwh  in file_processing.py should return True if successful; otherwise False
- process_samples should then only update DART if the add_to_dart flag is specified, and the MLWH insert was successful
- Add two new tests or process_samples : one to check DART is updated if MLWH insert is successful, the other one DART isn't updated if MLWH insert fails
