### ISSUE TITLE
GPL-820 near real time SFTP plate map data for Beckman platform (Incremental crawl) 

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#219]
**User story**
As LIMS team we would like to incrementally crawl SFTP on every upload from each Lighthouse lab to enable a near real time record of plate map data for daily Beckman cherry picking.  
 
**Who are the primary contacts for this story**
Ben F (Ops)
Rich C (Ops)

**Draft Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Poll SFTP for each change
- [ ] Update MongoBD, MLWH & DART (Small incremental updates are expected to be faster eg each update would not take 15-30 mins *1)

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
From conversation in stand up on 19th January. Issue identified by Ben F

Box 'lw-uk-biocentre-box-gsw-430-18953', contained 18 plates with plate map data, however 20 plates without. Of the first 3 plates that were checked without plate map data, GLA090362R, GLA090364R & GLA090378R, plate map data did exist in the file uploaded at 6am on 19th, but wont be parsed to 20th.

*1 Timings and schedule today (19th Jan) 

01:00 Core LIMS begins parse of SFTP plate maps, populates in order local crawler mongobd, MLWH & Beckman DART database (completes ~ 01:30)
02:00 Core LIMS begins to generate automated +ves onsite report from mongodb data parsed at 01:00 (completes ~ 02:15)
03:15 AP upload plate map (Consistent since 12th Sept)
04:00 PAM run process for PHE
06:00 GLAS upload plate maps (Consistent since 20th Dec)
06—09:00 CB upload plate map (Inconsistent timings)
09:00 MK upload plate map (Consistent since 4th August)
09:30 Operations start CP process for day - typically generate new +ves on site report, but missing AP, GLAS & MK from that morning, so operation often ‘working day behind’ available plate map data – physical plates on site however

**Comment by KatyTaylor** [comment]
Update:

Deployed a version of crawler that is scheduled to run every 15 minutes into UAT on 11th Feb just before 2pm.
Seems to be working OK, has processed the following since then:

uploaded to sftp | processed by crawler (from 'imports' page) | file
-- | -- | --
11th 09:01 | ~14:20 (first run since deployment) | MK_sanger_report_210211_0800.csv
11th 07:59 | ~14:20 (first run since deployment) | many Cambridge ones
12th 03:15 | ~03:30 | AP_sanger_report_210212_0130.csv
12th 06:00 | ~06:25 | GLS_sanger_report_210212_0500.csv
12th 08:04 | ~08:10 | many Cambridge ones
12th 09:01 | ~09:25 | MK_sanger_report_210212_0800.csv
manual run to make test data | ~10:50 | AP_sanger_report_210212_1049.csv

Only problem noticed was that the logging in kibana was very verbose due to lots of the following lines:

> "Checking file {file_name}"

> "File already processed successfully, skipping"

Deployed a new version to UAT to reduce this logging, today (12th) at around 12:30
the previous logs are gone, but the following lines are still quite chatty:

> "WARNING Found an identical file AP_sanger_report_201025_0001.csv in path errors which has the same checksum but a different filename"

(repeated for 32 different files)
