### ISSUE TITLE
GPL-854 parse non zero padded co-ordinates in 'RNA ID' values in plate maps from Biomeks (Cambridge)

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#253]
**User story**
GPL-854 | As LH Stakeholder (Alan K) I would like the well ordinate on 'RNA ID' to parse non zero padded co-ordinates because is a Biomek issue and cannot be fixed in-house at Cambridge (and Biomek consolidate plate are future strategy for LH)

**Who are the primary contacts for this story**
Alan K (PAM)
Rich L

**Context**
Cambridge moved from plates of positives, negatives and voids to consolidated plates on 4th February. Where previously the plate map RNA ID had plate map and well position concatenated with 0 padding eg EGC000035_A01 this is no longer the case with Biomek. RNA ID with no padding, now needs to be parsed eg EGC000035_A1

The is resulting in all samples being rejected as type 9 errors:

- http://lighthouse-ui.psd.sanger.ac.uk/imports (search on CB, look dates from 4th)
- Failed regex on plate barcode errors (TYPE 9): https://ssg-confluence.internal.sanger.ac.uk/x/jqsKBg (table 3.1)

Alan K wrote (Tuesday, 9 February 2021 at 09:39) 

_Padded zero issue is a Biomek issue and cannot be fixed in-house at Cambridge.
 
Because of this they supposedly checked directly with your team if this would be an issue when setting up the CP programme, and were informed that it would not cause issue due to code that runs during the file upload that accounts for the lack of the leading zero._

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Allow non zero errors to be parsed eg EGC000035_A1 and EGC000035_A01
- [ ] Update documentation https://ssg-confluence.internal.sanger.ac.uk/x/jqsKBg (table 3.1)
- [ ] Update  GPL-846 Document de facto plate map standard in pdf to improve Sanger LH communication #246

**Comment by neilsycamore** [comment]
Backfill lighthouse_sample table.
Issue with Cambridge samples uploaded by manifest e.g. EGC000013
Only 22 samples are in table (A10,11,12.. H11 etc) but all samples (A1..H11) have been pooled and gone through to be sequenced

**Comment by emrojo** [comment]
I think the set of tasks is this, but first try in UAT:
- [ ] Update regular expression in Crawler for the Cambridge center (or maybe for all centers) to allow new syntax
- [ ] Get the list of files that has a TYPE 9 error from the imports view in Lighthouse UI (every file from Cambridge since 5/Feb/2021, you can see the problem because number of imports is very log < 100 samples)
- [ ] From that list of files, search for them in  /var/lib/crawler/backups/CAMC/errors and then a) change filenames, or b) move the files out of the folder, or c) remove the files(Crawler will not reprocess if the file and timestamp is in this folder)
- [ ] Rerun again crawler ```python runner.py --sftp --add-to-dart```
