### ISSUE TITLE
GPL-591 Admin ban list in database for crawler process

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#75]
**User story**
In the crawler, the blacklist is stored in database, but is not used in actual process from database, but from the file, so we have to redeploy everytime we change the black list. Change it behaviour to read from database instead.

**Who are the primary contacts for this story**
Eduardo Martin

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Read the blacklist from the database

**Comment by stevieing** [comment]
Need to wait until Monday for the refactor of #66

**Comment by KatyTaylor** [comment]
- Extra columns break the process because all files are merged into a one single file and the resulting csv is not right. Add a way of filtering out this extra columns from the merging process.
- When a file is wrong the app throws an exception, however it doesnt say which file, so we have to run the process again from the console to see where it was the problem. Add the filename in the exception message

- [x] Ignore extra columns (See backlog item GPL-567)
- [x] Log errored filename in exceptions(See backlog item GPL-568)
